version: 1
name: base-flood
dataset: ../dataset/flood.yaml
sampler: ../sampler/flood.yaml
model: ../model/sampleconvnext.yaml
scheduler: ../scheduler/reduceLR.yaml
optimizer: ../optimizer/adamw.yaml
criterion: ../criterion/flood.yaml